import AppKit

/// Polls the general pasteboard (macOS has no change notification) and reports new content.
final class ClipboardMonitor {
    var onCapture: ((Captured, _ sourceBundleID: String?) -> Void)?
    var onTick: (() -> Void)?

    private let pasteboard = NSPasteboard.general
    private var lastChangeCount: Int
    private var timer: Timer?

    /// Pasteboard types that mark content as secret or transient (password managers, etc.).
    private static let ignoredTypes: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
        "com.agilebits.onepassword",
        "com.typeit4me.clipping",
        "de.petermaurer.TransientPasteboardType",
        "Pasteboard generator type",
    ]

    private static let maxTextBytes = 5_000_000
    private static let maxRTFBytes = 262_144
    private static let maxImageBytes = 40_000_000

    init() {
        lastChangeCount = pasteboard.changeCount
    }

    func start() {
        guard timer == nil else { return }
        let timer = Timer(timeInterval: 0.5, repeats: true) { [weak self] _ in self?.tick() }
        RunLoop.main.add(timer, forMode: .common)
        self.timer = timer
    }

    /// Call right after this app writes to the pasteboard so its own write is not re-captured.
    func skipCurrentChange() {
        lastChangeCount = pasteboard.changeCount
    }

    private func tick() {
        onTick?()
        let count = pasteboard.changeCount
        guard count != lastChangeCount else { return }
        lastChangeCount = count
        guard let captured = read() else { return }
        let source = NSWorkspace.shared.frontmostApplication?.bundleIdentifier
        onCapture?(captured, source)
    }

    private func read() -> Captured? {
        guard let types = pasteboard.types else { return nil }
        let typeNames = Set(types.map(\.rawValue))
        guard typeNames.isDisjoint(with: Self.ignoredTypes) else { return nil }

        // 1. Files copied in Finder.
        if types.contains(.fileURL) {
            let objects = pasteboard.readObjects(forClasses: [NSURL.self], options: [.urlReadingFileURLsOnly: true]) ?? []
            let paths = objects.compactMap { ($0 as? URL)?.path }
            if !paths.isEmpty { return .files(paths) }
        }

        let hasImage = types.contains(.png) || types.contains(.tiff)
        let hasString = types.contains(.string)
        let hasRTF = types.contains(.rtf)

        // 2. Images. Office apps put a bitmap rendering next to rich text; prefer the text there.
        if hasImage, !(hasString && hasRTF), let image = readImage() {
            return image
        }

        // 3. Plain text (with RTF kept alongside when it is reasonably small).
        if hasString, let string = pasteboard.string(forType: .string),
           !string.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty,
           string.utf8.count <= Self.maxTextBytes {
            var rtf = hasRTF ? pasteboard.data(forType: .rtf) : nil
            if let data = rtf, data.count > Self.maxRTFBytes { rtf = nil }
            return .text(string, rtf: rtf)
        }

        if hasImage, let image = readImage() {
            return image
        }
        return nil
    }

    private func readImage() -> Captured? {
        var png = pasteboard.data(forType: .png)
        if png == nil, let tiff = pasteboard.data(forType: .tiff), let rep = NSBitmapImageRep(data: tiff) {
            png = rep.representation(using: .png, properties: [:])
        }
        guard let data = png, data.count <= Self.maxImageBytes, let rep = NSBitmapImageRep(data: data) else {
            return nil
        }
        return .image(png: data, width: rep.pixelsWide, height: rep.pixelsHigh)
    }
}
